### ISSUE TITLE
Server monitor called with an empty session state

### ISSUE THREAD

**Issue by brettwinters** [sotsera/sotsera.blazor.oidc#14]
Hi @ghidello 

Just testing your library using different IDP's - but I've run into a problem 

![image](https://user-images.githubusercontent.com/26474006/71900597-b0d4a900-3190-11ea-8817-ebcc7990b208.png)

I'm using Okta with Code Flow w. PKCE. Both popup and redirect. Server logs say I've signed in ok and (I think) swapped the access token. If I swap the settings for your IdentityServer demo then no errors... 

Any Ideas? 

Regards

Brett

**Comment by ghidello** [comment]
Ciao @brettwinters,
looking at the error and from what i quickly saw in the okta site, I think that it does not support the OpenID Connect Session Management 1.0 protocol (if that's the case probably the logout functionality will not work eighter)
You can try disabling the session manager using this configuration setting:

```csharp
settings.MonitorSession = false;
```
Let me know if you'll be able to make it work and maybe you can add a recipe for Okta in this [issue](https://github.com/sotsera/sotsera.blazor.oidc/issues/2) (one day it will become part of the documentation, hopefully)

**Comment by brettwinters** [comment]
Thanks, @ghidello - yup, disabling the Session Management worked! I will add to the recipes...

For the Logout - The user-initiated logout works for Okta, but not when I tested with Auth0 (which also needs Session Management disabled)

![image](https://user-images.githubusercontent.com/26474006/71959334-15d9de80-3225-11ea-97ec-93f32eeb61cb.png)

Regards

Brett

**Comment by ghidello** [comment]
I'm glad it worked. I'll have to change the implementation flow for handling the Auth0 logout use case cleanly.
Do you think we can close this?

**Comment by brettwinters** [comment]
ok, that will be great - I'll look forward to the fix. I may ask some follow up questions later about impact of disabling session management after I try a few scenarios...

**Comment by ghidello** [comment]
Sure, I'll be interested in your suggestions for better handling different scenarios. 
I'll have some time these days and I started rethinking the whole library. 
So feel free to add any thoughts to issue #15
