### ISSUE TITLE
Multiple usage of OidcHttpClient fails with token not available 

### ISSUE THREAD

**Issue by ChristianWeyer** [sotsera/sotsera.blazor.oidc#17]
When using OidcHttpClient in a Blazor page like /conferences directly in the .razor file everything seems fine.

When I add another page for e.g. /conference/{id} which then, in turn, uses a custom service which then uses OidcHttpClient (all via DI), then this instance of OidcHttpClient does not pick up the token when doing API calls.

**Comment by ChristianWeyer** [comment]
I just changed my application to only use OidcHttpClient with DI in my service. Actually, this does not seem to work at all when I use OidcHttpClient in my own custom service via DI. The token is not picked up.

**Comment by ChristianWeyer** [comment]
One more update :-)
It works when I register my custom service as scoped in DI. I had it as singleton originally.

**Comment by ghidello** [comment]
Yes, singleton services and scoped dependencies are an explosive mix: I've been burned by it too! :smile:

**Comment by ChristianWeyer** [comment]
😅🔥
